### ISSUE TITLE
Unit and acceptance tests broken upgrading to Helm v3.5.(2?/3?)

### ISSUE THREAD

**Issue by jdolitsky** [helm/chartmuseum#430]
The semver validation appears to be strictly enforced using `loader.LoadArchive`

This line causes 500: https://github.com/helm/chartmuseum/blob/main/pkg/repo/chart.go#L52

cc @scbizu

**Comment by scbizu** [comment]
hmm ... It seems that the broken test caused by the path error , and the `testdata/badcharts/mybadsemver2chart/mybadsemver2chart-0.x.x.tgz` archive file is missing

**Comment by scbizu** [comment]
It is weird that only the mybadsemver2chart not be packaged , maybe re-run makes sense ?

**Comment by scbizu** [comment]
And I found why , the fork version https://github.com/bloodorangeio/chartmuseum/tree/0-13-1-prep/testdata/charts do not have mybadsemver2chart dir . Can you fix it @jdolitsky ?

**Comment by jdolitsky** [comment]
@scbizu - the issue is the test setup script was not building the .tgz. I fixed this in this commit https://github.com/helm/chartmuseum/commit/65f7482f9a49b589652a2f7141459af0941a006f

Now the error is this:
```
    server_test.go:683: 
        	Error Trace:	server_test.go:683
        	Error:      	Not equal: 
        	            	expected: 400
        	            	actual  : 500
        	Test:       	TestMultiTenantServerTestSuite/TestSemver2Validation
        	Messages:   	400 POST /api/charts bad semver validation
```
        	
https://github.com/helm/chartmuseum/pull/429/checks?check_run_id=2091220693

The 500 is thrown because helm libraries will not parse the binary content into a chart due to strict semver check

**Comment by scbizu** [comment]
I see , the Helm latest helm [commit](https://github.com/helm/helm/commit/657ce552cb6e582976c08cccc9605e42c242084e) forces the semantic version . For me . I think it is a good approach , it means that we can deprecated the  `--force-semver2` flag , and let it depend on the helm's validation.

But since v0.13.1 is a bug fix release , we should modify our go.mod to depend on the lower version of helm `pkg/chart/loader` to make our action pipeline happy and make this break changes in 0.14.0 maybe ?

**Comment by jdolitsky** [comment]
@scbizu sure, that sounds good. just updated #429
