### ISSUE TITLE
Review use of docker buildx in CI

### ISSUE THREAD

**Issue by jdolitsky** [helm/chartmuseum#539]
The current build takes over 1 hour. Perhaps at the very least the buildx build and push steps can combined?

**Comment by cbuto** [comment]
@jdolitsky 👀 I was taking a peek at this and planning on putting up a PR with a proposal at some point. I think if we build all the chartmuseum binaries (`make cross-build`) and copy them into the images (depending on the `TARGETARCH`), we can speed up the docker builds (which seem to take a lot of time due to having to download the go modules each time).

**Comment by scbizu** [comment]
@cbuto It seems already existed in Makefile which called make-cross ?  We only need to fix our action to use the build-cross and remove the in docker build (which no module cache per platform build) and adjust the docker mv command 🤔

**Comment by cbuto** [comment]
@scbizu yup! that's exactly what I was thinking, I have a branch that is close to working just trying to test it locally 🚀

**Comment by cbuto** [comment]
The last build took `27m 5s`! I tested a few different architectures and everything appears to be working as expected 🎉

**Comment by jdolitsky** [comment]
phenomenal. Great work @cbuto. think we shall close this for now
